### ISSUE TITLE
Add ability to run custom command upon connection.

### ISSUE THREAD

**Issue by shacknetisp** [IceflowRE/irc-discord-relay#1]
Example command would be a nickserv identify message or vhost command.

**Comment by IceflowRE** [comment]
Could you give an example how vhost would work?

**Comment by shacknetisp** [comment]
An example VHOST command would be (on my IRC server): `VHOST some_id secret_key`
So it's not a private message like NickServ (`PRIVMSG NickServ identify some_id secret_key`)
